import SearchLayoutHeader from '@/components/SearchComponents/SearchLayoutHeader';
import React from 'react'
import SubmitForm from './SubmitForm/SubmitForm';
import ImageData from './Datatable/ImageData';

export const metadata = {
    title: "FPR - Image",
    description: "Generated by create next app",
};
function Image() {
    return (
        <>
            <SearchLayoutHeader title={"Image Search"} />
            <SubmitForm />
            <ImageData />
        </>
    )
}

export default Image