import React from 'react'

export const metadata = {
    title: "FPR - LNV",
    description: "Generated by create next app",
};
function LNV() {
    return (
        <div>LNV</div>
    )
}

export default LNV