import React from 'react'

export const metadata = {
    title: "FPR - Notary",
    description: "Generated by create next app",
};
function Notary() {
    return (
        <div>Notary</div>
    )
}

export default Notary