import React from 'react'

export const metadata = {
    title: "FPR - Combo",
    description: "Generated by create next app",
};
function Combo() {
    return (
        <div>Combo</div>
    )
}

export default Combo