import SearchLayoutHeader from '@/components/SearchComponents/SearchLayoutHeader';
import React from 'react'
import SubmitForm from './SubmitForm/SubmitForm';
import ApnData from './Datatable/ApnData';

export const metadata = {
    title: "FPR - APN",
    description: "Generated by create next app",
};
function APN() {
    return (
        <>
            <SearchLayoutHeader title={"APN Search"} />
            <SubmitForm />
            <ApnData />
        </>
    )
}

export default APN