import React from 'react'

export const metadata = {
    title: "FPR - AVR",
    description: "Generated by create next app",
};
function AVR() {
    return (
        <div>AVR</div>
    )
}

export default AVR