import React from 'react'

export const metadata = {
    title: "FPR - Business Entity",
    description: "Generated by create next app",
};
function BusinessEntity() {
    return (
        <div>Business Entity</div>
    )
}

export default BusinessEntity