import SearchLayoutHeader from '@/components/SearchComponents/SearchLayoutHeader';
import React from 'react'
import SubmitForm from './SubmitForm/SubmitForm';

export const metadata = {
    title: "FPR - Property Search",
    description: "Generated by create next app",
};
function PropertySearch() {
    return (
        <>
            <SearchLayoutHeader title={"Property"} />
            <SubmitForm />
        </>
    )
}

export default PropertySearch