
import Link from 'next/link'
import React from 'react'
import loginImage from "@/public/resetpassword.svg"
import Image from 'next/image'
import Form from './Form'

export const metadata = {
    title: 'FPS - Forget Password',
    description: 'Generated by create next app',
}


const ForgetPassword = () => {

    return (
        <main className='min-h-[100vh] flex items-center'>
            <div className='w-[80%] mx-auto justify-between flex  items-center flex-wrap'>
                <div className='w-full lg:w-[40%]'>
                    <div className='lg:mb-10 mb-5 text-center space-y-2'>
                        <h5 className='text-xl font-semibold'>Forgot Your Password?</h5>
                        <p className='text-sm font-light tracking-wider'>Enter Your Registered email below to receive
                            password reset instruction</p>
                    </div>
                    <Form />
                    <div className=' text-sm mt-2'>
                        <span>Remember Password?</span> <Link className='text-blue-600' href={"/login"} >Login</Link>
                    </div>
                </div>
                <div className='w-full lg:w-[49%]  mt-5 sm:flex sm:justify-center lg:flex-none lg:justify-start'>
                    <div className='flex  justify-center items-center  w-full'>
                        <Image className='my-2 mx-auto' src={loginImage} width={450} alt='login page image' />
                    </div>
                </div>
            </div>
        </main>
    )
}

export default ForgetPassword