import React from 'react'

export const metadata = {
    title: "FPR - Judgement",
    description: "Generated by create next app",
};
function Judgement() {
    return (
        <div>Judgement</div>
    )
}

export default Judgement