import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'
dynamic(() => import('./style.css'), { ssr: false })

const ReduxStore = dynamic(() => import('@/Providers/ReduxStore'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'FPS - Login',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <ReduxStore>
                    {children}
                </ReduxStore>
            </body>
        </html>
    )
}
