import React from 'react'

export const metadata = {
    title: "FPR - Starter",
    description: "Generated by create next app",
};
function Starter() {
    return (
        <div>Starter</div>
    )
}

export default Starter