import Tablink from "@/components/TabLink/Tablink";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const menu = [
    {
        link: '/search/property-search',
        lable: "Property Search"
    },
    {
        link: '/search/grantor-grantee',
        lable: "Grantor Grantee"
    },
    {
        link: '/search/apn',
        lable: "APN"
    },
    // {
    //     link: '/search/lnv',
    //     lable: "LnV"
    // },
    // {
    //     link: '/search/avr',
    //     lable: "AVR"
    // },
    {
        link: '/search/instrument',
        lable: "Instrument"
    },
    {
        link: '/search/image',
        lable: "Image"
    },
    // {
    //     link: '/search/starter',
    //     lable: "Starter"
    // },
    // {
    //     link: '/search/judgement',
    //     lable: "Judgement"
    // },
    // {
    //     link: '/search/notary',
    //     lable: "Notary"
    // },
    // {
    //     link: '/search/combo',
    //     lable: "Combo"
    // },
    // {
    //     link: '/search/business-entity',
    //     lable: "Business Entity"
    // },
]
export default function SearchLayout({ children }) {

    return (
        <div>
            <nav className="bg-gray-100 text-[13px] font-semibold rounded-t-md ps-0.5 shadow-sm border-b">
                <ul className="flex flex-wrap sm:space-y-2 lg:space-y-0">
                    {
                        menu.map(({ link, lable }, index) => {
                            return <li key={link}>
                                <Tablink lable={lable} border={index + 1 !== menu.length} link={link} />
                            </li>
                        })
                    }
                </ul>
            </nav>
            <section className='b-white shadow p-2 my-4  rounded-md border text-b-sm'>
                {children}
            </section>
        </div>
    );
}
